### PR TITLE
feat: design a mobile responsive travel page

### LINKED ISSUE #179: Add the Travel page
Feature: We need to design the travel page.
Find the new design [here](https://www.figma.com/file/uGbiNNx3nZqONJ7qBKORkG/website-%26-stage?node-id=291-2)

Guidelines:

In the repository, find the 2023 sub-folder in src. Please do not change files that are not related to this feature except when updating configurations or fixing a bug.
In the components folder, find the 2023 sub-folder and create the components you will need for the travel page.
We use Tailwind CSS; kindly complete the designs with Tailwind only.
Import the components where needed in the pages sub-folder of the 2023 folder.
If possible, write tests; however, this should not hinder you from contributing as the team regularly updates tests.
Special Note: Take note of mobile designs. We prefer a mobile-first approach.

If you have any questions, ask @BolajiAyodeji or @Princesso

Thank you

### PR DESCRIPTION
**Pull request by t-bello7**
#### What does this PR do
- This PR will ship code changes made to build the Sustain Africa 2023 Travel page.
- Implements the OSCA 2023 Travel Page From [Figma Board](https://www.figma.com/file/uGbiNNx3nZqONJ7qBKORkG/website-%26-stage?node-id=291-2)
#### Description of Task to be completed
[x] Build page header component
[x] Build page text sections
[x] Build Accommodation List
[x] Add Tailwind classes for mobile responsiveness.
#### How should this be manually tested
Pull the travel-guide-page branch and navigate to the new sustain event page at http://localhost:8000/2023/travel/.

#### What are the relevant issues this PR belongs to
- Fixes #179

#### Screenshots
- Desktop View
Screenshot 2023-06-04 at 06-31-14 Open Source Festival 2023
- Mobile View
Screenshot 2023-06-04 at 06-31-44 Open Source Festival 2023

### CODE REVIEW

**Comment by Princesso** [comment]
Hi @t-bello7 thank you so much for your contribution. 
I tested this page using the preview link and some of the styles look a bit off. Can you click on the preview link and have a look? 
Here's the [link](https://deploy-preview-190--osca-festival.netlify.app/)

**Comment by t-bello7** [comment]
Thank you @Princesso for the review. I was having a classic case of it works on my machine but doesn't work in production. Can you kindly review the pull request?

**Review by Princesso — APPROVED** [review]

**Comment by Princesso** [comment]
@t-bello7 can you please pull the latest version of the main branch to resolve conflicts, after which we can merge it in today?
Thank you.

**Comment by BolajiAyodeji** [comment]
Hi @t-bello7, the content on this page is stale. If I provide you with a document with new content, can you update this soonest? Thank you.

**Comment by t-bello7** [comment]
> Hi @t-bello7, the content on this page is stale. If I provide you with a document with new content, can you update this soonest? Thank you.

Yes @BolajiAyodeji .You can send it to my email at bello4aus@outlook.com

**Pull request merged**
