### PR TITLE
feat: complete MVP of sustain-africa page 2023

### PR DESCRIPTION
**Pull request by vickywane**
#### Description of Task to be completed
This PR will ship code changes made to build the Sustain Africa 2023 Event page. 

#### How should this be manually tested: 

Pull the `feat/sustain-event-page` branch and navigate to the new sustain event page at `http://localhost:8000/2023/sustain-africa/`.

#### What are the relevant issues this PR belongs to

#178 

#### Tasks: 
- [x] Build hero component.
- [x] Build page text sections.
- [x] Build Agenda / Schedule table.
- [x] Add Tailwind classes for mobile responsiveness.

### CODE REVIEW

**Comment by vickywane** [comment]
@Princesso @BolajiAyodeji Keeping this PR as a draft since I'm yet to build out the Agenda table alongside mobile responsiveness.

**Comment by vickywane** [comment]
@Princesso @BolajiAyodeji Do I need to build the agenda table or is that dynamically embedded from [Sched](https://sched.com/) through the `ScheEmbed.js` component?

**Comment by BolajiAyodeji** [comment]
> @Princesso @BolajiAyodeji Do I need to build the agenda table or is that dynamically embedded from [Sched](https://sched.com/) through the `ScheEmbed.js` component?

Hi @vickywane. You don't need to build the schedule table; it's embedded from Sched, as you mentioned.

**Comment by BolajiAyodeji** [comment]
> @Princesso @BolajiAyodeji Do I need to build the agenda table or is that dynamically embedded from [Sched](https://sched.com/) through the `ScheEmbed.js` component?

Hi @vickywane. Yes, you need to build the agenda schedule table for this page. You can find the content of the table in [this document ](https://docs.google.com/document/d/1_5mXEkztTvsxCV0kJeaFHLssH1GEAmPsu24lcsmh-ZM/edit?usp=sharing)(PS: the table is all you need to take out from this document). Thank you.

**Comment by vickywane** [comment]
@Princesso @BolajiAyodeji This is ready for a code review and QA.

I'll be glad to fix any UI issues raised.

**Pull request merged**
